[project]
name = "hv-bie"
version = "0.1.0"
description = "HentaiVerse battle information extractor"
authors = [{name = "HV-BIE"}]
requires-python = ">=3.13"
dependencies = ["beautifulsoup4"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
